name: Mi primer CI en github actions

on:
  push:
    branches: ["main"]
  
jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:

      - name: saludamos al mundo
        run: echo "Hola mundo desde github actions"

      - uses: actions/checkout@v5

      - name: localizamos la IP de origen
        run: curl ifconfig.me

      - name: que hora es dentro del runner
        run: date

      - name: haz un listado del directorio
        run: ls -la